# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    ssh-keyscan magerit.cesvima.upm.es >> ~/.ssh/known_hosts
    chmod 600 $SSH_PRIVATE_KEY
    ssh -i $SSH_PRIVATE_KEY t584608@magerit.cesvima.upm.es "cd /home/t584/t584608 && bash uvigo_quant.sh"
  env:
    SSH_PRIVATE_KEY: $(SSH_PRIVATE_KEY)
