trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: deploy_to_cevisma
  displayName: 'Deploy to Cevisma'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      architecture: 'x64'
  - script: |
      sudo apt-get update
      sudo apt-get install openssh-client -y
      ssh -i $SSH_PRIVATE_KEY t584608@magerit.cesvima.upm.es "cd /home/t584/t584608 && bash uvigo_quant.sh"
    env:
      SSH_PRIVATE_KEY: $(SSH_PRIVATE_KEY)